//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleWeb {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExampleWeb.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {1}では&apos;{0}&apos;は無効な値です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AttemptedValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("AttemptedValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}と{1}が一致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompareAttribute {
            get {
                return ResourceManager.GetString("CompareAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は正しいカード番号ではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreditCardAttribute {
            get {
                return ResourceManager.GetString("CreditCardAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は正しいメールアドレスではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmailAddressAttribute {
            get {
                return ResourceManager.GetString("EmailAddressAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は正しい電話番号ではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PhoneAttribute {
            get {
                return ResourceManager.GetString("PhoneAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}から{2}の範囲で指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RangeAttribute {
            get {
                return ResourceManager.GetString("RangeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は正規表現&apos;{1}&apos;に一致するように指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegularExpressionAttribute {
            get {
                return ResourceManager.GetString("RegularExpressionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequiredAttribute {
            get {
                return ResourceManager.GetString("RequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}桁以内で指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringLengthAttribute {
            get {
                return ResourceManager.GetString("StringLengthAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は正しいURLではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UrlAttribute {
            get {
                return ResourceManager.GetString("UrlAttribute", resourceCulture);
            }
        }
    }
}
